### ISSUE TITLE
Lenovo model name

### ISSUE THREAD

**Issue by sandytsang** [NickolajA/PowerShell#1]
Hello, I just wonder in the script model name is 
$ComputerModel = Get-WmiObject -Class Win32_ComputerSystem | Select-Object -ExpandProperty Model

So when I have Lenovo T460s, $ComputerModel is 20FAS1NF00, Driver package name in CM is Drivers - Lenovo Thinkpad T460s - Win10 x64, so there is no way they can match. 

I have not testing yet install Lenovo machine, just checking out the script. 
I think for Lenovo, need to use $ComputerModel = Get-WmiObject -Class Win32_ComputerSystemProduct | Select-Object -ExpandProperty Version

Oh, BTW, I am not using the web service portal, I don't know if the web service portal somehow convert those Lenovo model to the correct names. :) 

I am using these directly get those packages informations out. (I don't want go to change board request build web service portal :) )
$Query = "Name LIKE 'Drivers - %'"
$Packages = Get-WmiObject -ComputerName $SiteServer -Class SMS_Package -Namespace root/sms/site_$sitecode -Filter $Query -Credential $Cred

**Comment by NickolajA** [comment]
Fixed :)
